name: tavus_avatar_example
description: Example app demonstrating Tavus Avatar Flutter package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.1
  http: ^1.2.1
  video_player: ^2.8.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  audioplayers: ^6.1.0
  # Keep Hive as optional cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  livekit_client: ^2.4.7
  percent_indicator: ^4.2.3
  # Use the local package
  avatar_sts2:
    path: ../packages/avatar/
  tracing_game:
    path: ../packages/tracing/
  cupertino_icons: ^1.0.8
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/images/flags/
    - assets/images/letters/
    - assets/audio/
    - assets/svg/
    - assets/tracing/
  fonts:
    - family: "Tufuli Arabic"
      fonts:
        - asset: assets/fonts/tufuli-regular.otf
        - asset: assets/fonts/tufuli-bold.otf
          weight: 700