name: tavus_avatar_example
description: Example app demonstrating Tavus Avatar Flutter package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.1
  http: ^1.2.1
  video_player: ^2.8.2
  # Use the local package
  avatar_sts2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/intro_final.mp4
    - assets/images/
    - assets/images/flags/
    - assets/images/letters/
    - assets/audio/
  fonts:
    - family: "Tufuli Arabic"
      fonts:
        - asset: assets/fonts/tufuli-regular.otf
        - asset: assets/fonts/tufuli-bold.otf
          weight: 700