// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpaToB7rPgqXga87N_2G_Tt7E5EpIw1WQ',
    appId: '1:295781367941:web:ed81f580af2123f53ea9ec',
    messagingSenderId: '295781367941',
    projectId: 'huda-v2',
    authDomain: 'huda-v2.firebaseapp.com',
    storageBucket: 'huda-v2.firebasestorage.app',
    measurementId: 'G-MFD4DK59PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'test-android-api-key',
    appId: 'test-android-app-id',
    messagingSenderId: '123456789',
    projectId: 'huda-lessons-test',
    storageBucket: 'huda-lessons-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'test-ios-api-key',
    appId: 'test-ios-app-id',
    messagingSenderId: '123456789',
    projectId: 'huda-lessons-test',
    storageBucket: 'huda-lessons-test.appspot.com',
    iosBundleId: 'com.example.tavusAvatarExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'test-macos-api-key',
    appId: 'test-macos-app-id',
    messagingSenderId: '123456789',
    projectId: 'huda-lessons-test',
    storageBucket: 'huda-lessons-test.appspot.com',
    iosBundleId: 'com.example.tavusAvatarExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'test-windows-api-key',
    appId: 'test-windows-app-id',
    messagingSenderId: '123456789',
    projectId: 'huda-lessons-test',
    authDomain: 'huda-lessons-test.firebaseapp.com',
    storageBucket: 'huda-lessons-test.appspot.com',
  );
}